### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by Ckitakishi** [brevansio/PRChecker#16]
# TODO/Feature Ideas
- [ ] Change background color of PR cells based on its read status

# Doing
- [ ] ⭐ Show PR count in menu bar

# Done
- [x] ❗️Icon
- [x] Improve design
- [x] ⭐ Sync data between PR list and menu bar PR list
- [x] ⭐ Add timer for refreshing data
- [x] Enable to customize timer in setting
